export const TOOL_NAMES = Object.freeze({
  GET_WEATHER: 'get_weather',
  CREATE_THREAD: 'create_thread',
  GET_GUILD_EVENTS: 'get_guild_events',
  REMEMBER: 'remember',
  RECALL: 'recall',
  FORGET_MEMORY: 'forget_memory',
  RUN_BASH: 'run_bash',
  GET_GAME_LISTING: 'get_game_listing',
  GET_EMOJIS: 'get_emojis',
  QUERY_SQLITE: 'query_sqlite',
  DESCRIBE_SCHEMA: 'describe_schema',
  GENERATE_IMAGE: 'generate_image',
  CREATE_GITHUB_ISSUE: 'create_github_issue',
  SEARCH_GITHUB_ISSUES: 'search_github_issues',
});
